export const cityList: any[] = [
    {name: 'KAŞ'},
    {name: 'LARA'},
    {name: 'MUĞLA'},
    {name: 'İZMİR'},
    {name: 'BELEK'},
    {name: 'DEMRE'},
    {name: 'ALANYA'},
    {name: 'ÇIRALI'},
    {name: 'FİNİKE'},
    {name: 'KEMER'},
    {name: 'KEPEZ'},
    {name: 'KALKAN'},
    {name: 'ANTALYA'},
    {name: 'ADRASAN'},
    {name: 'KALEİÇİ'},
    {name: 'KUMLUCA'},
    {name: 'OLİMPOS'},
    {name: 'İSTANBUL'},
    {name: 'MANAVGAT'},
    {name: 'BALIKESİR'},
    {name: 'KONYAALTI'},
    {name: 'MURATPAŞA'},
    {name: 'DÖŞEMEALTI'},
    {name: 'ANTALYA MERKEZ'},
];

export const typeList: any[] = [
    {name: 'DOĞA'},
    {name: 'GENÇ'},
    {name: 'GOLF'},
    {name: 'DAĞ'},
    {name: 'ŞEHİR'},
    {name: 'KONSEPT'},
    {name: 'DELUXE'},
    {name: 'BALAYI'},
    {name: 'İSLAMİ'},
    {name: 'SİNGLE'},
    {name: 'RESORT'},
    {name: 'EKONOMİK'},
    {name: 'ALKOLSÜZ'},
    {name: 'AQUAPARK'},
    {name: 'BULGALOV'},
    {name: 'ROMANTİK'},
    {name: 'KUM PLAJI'},
    {name: 'BUTİK OTEL'},
    {name: 'DOĞA DOSTU'},
    {name: 'GOLF OTELİ'},
    {name: 'SPA TESİSİ'},
    {name: 'ŞEHİR OTELİ'},
    {name: 'TATİL  KÖYÜ'},
    {name: 'BEBEK DOSTU'},
    {name: 'BEBEK DOSTU'},
    {name: 'ÇEVRE DOSTU'},
    {name: 'ÇOCUK DOSTU'},
    {name: 'HERŞEY DAHİL'},
    {name: 'TEMATİK OTEL'},
    {name: 'HAYVAN DOSTU'},
    {name: 'KONGRE OTELİ'},
    {name: 'ODA KAHVALTI'},
    {name: 'DENİZE SIFIR'},
    {name: 'ÇOCUKLU AİLE'},
    {name: 'DENİZE SIFIR'},
    {name: 'SU KAYDIRAĞI'},
    {name: 'TAM PANSİYON'},
    {name: 'ODA KAHVALTI'},
    {name: 'BALAYI OTELİ'},
    {name: 'DENİZE SIFIR'},
    {name: 'HER ŞEY DAHİL'},
    {name: 'ROMANTİK OTEL'},
    {name: 'EĞLENCE OTELİ'},
    {name: 'ENGELLİ DOSTU'},
    {name: 'MAVİ BAYRAKLI'},
    {name: 'YARIM PANSİYON'},
    {name: 'YETİŞKİN OTELİ'},
    {name: 'KÜÇÜK ve BUTİK'},
    {name: 'AQUAPARK OTELİ'},
    {name: 'GENÇ DOSTU OTEL'},
    {name: 'HAVAALANI OTELİ'},
    {name: 'MUHAFAZAKAR OTELİ'},
    {name: 'ÖZEL SAĞLIK TALEBİ'},
    {name: 'ULTRA HERŞEY DAHİL'},
    {name: 'SPA (Selus Per Aqua)'},
    {name: 'İLERİ YAŞ DOSTU TELİ'},
    {name: 'ÇEVREYE DUYARLI TESİS'},
    {name: 'EVCİL HAYVAN KABUL EDEN'},
    {name: 'TEKERLEKLİ SANDALYE UYGUN'},
    {name: 'ALKOLSÜZ HİZMAET VEREN TESİS'},
];

export const adultOfPeopleList: any[] = [
    {count: 1, isChecked: false},
    {count: 2, isChecked: false},
    {count: 3, isChecked: false},
    {count: 4, isChecked: false},
    {count: 5, isChecked: false},
    {count: 6, isChecked: false},
];

export const childOfPeopleList: any[] = [
    {count: 0, isChecked: false},
    {count: 1, isChecked: false},
    {count: 2, isChecked: false},
    {count: 3, isChecked: false},
];


export const budgetPayStart: any[] = [
    {count: 0, isChecked: false},
    {count: 1000, isChecked: false},
    {count: 3000, isChecked: false},
    {count: 5000, isChecked: false},
    {count: 7000, isChecked: false},
    {count: 10000, isChecked: false},
    {count: 15000, isChecked: false},
    {count: 20000, isChecked: false},
    {count: 25000, isChecked: false},
    {count: 30000, isChecked: false},
    {count: 35000, isChecked: false},
    {count: 40000, isChecked: false},
    {count: 45000, isChecked: false},
    {count: 50000, isChecked: false},
    {count: 55000, isChecked: false},
    {count: 60000, isChecked: false},
];

export const budgetPayEnd: any[] = [
    {count: 1000, isChecked: false},
    {count: 3000, isChecked: false},
    {count: 5000, isChecked: false},
    {count: 7000, isChecked: false},
    {count: 10000, isChecked: false},
    {count: 15000, isChecked: false},
    {count: 20000, isChecked: false},
    {count: 25000, isChecked: false},
    {count: 30000, isChecked: false},
    {count: 35000, isChecked: false},
    {count: 40000, isChecked: false},
    {count: 45000, isChecked: false},
    {count: 50000, isChecked: false},
    {count: 55000, isChecked: false},
    {count: 60000, isChecked: false},
    {count: 'ÜZERİ', isChecked: false}
];
